<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>generated</CompilerGeneratedFilesOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);generated/**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CoreAssembly">
      <HintPath>C:\Users\fangz\AppData\Roaming\AllOut\665126302460f089e87b2577-editor/res/CoreAssembly.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="C:\Users\fangz\AppData\Roaming\AllOut\665126302460f089e87b2577-editor/res/SourceGenerator/SourceGenerator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
